@ACCESS_TOKEN=Bearer eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDA2MTE5NTcsImV4cCI6MTYwMTIxNjc1NywiYXVkIjoiNWY2NWU1ZjQ4MWM5YTMzMzU4OGZkMTZmIiwiaXNzIjoicmF3c29sdXRpb25zLmluIn0.Tf9gBr4ocvmhC4uDV39lgDaUw_xZ9ixeKIQkodaqLdk
@REFRESH_TOKEN="refresh token"



### Home Page ###
GET http://localhost:3000/
content-type: application/json,













### Home Page ###
GET http://localhost:3000/ping
content-type: application/json,














### User Registration Submit ###
POST  http://localhost:3000/api/register
content-type: application/json

{
    "firstname":"Ayantika",
    "lastname":"Das",
    "email":"abcdaaa@gmail.com",
    "password":"abcd"

}










### User Login Submit ###
POST  http://localhost:3000/api/login
content-type: application/json

{    
    "email":"abcd@gmail.com",
    "password":"abcd"
}








### User's Dashboard
GET http://localhost:3000/api/users
content-type: application/json
authorization: {{ACCESS_TOKEN}}










### User's Logout
POST http://localhost:3000/api/logout
content-type: application/json,
authorization: {{ACCESS_TOKEN}} 

{
    "refresh_token": ""
}







### New Request ###
GET http://localhost:3000/unknown






### All Clubs
GET http://localhost:3000/api/clubs




### All Clubs
POST http://localhost:3000/api/clubs/register
content-type: application/json

{

}